export enum SharedInfrastructureDiToken {
  TEMPLATE_SERVICE = "TEMPLATE_SERVICE",
  FILE_SERVICE = "FILE_SERVICE",
  SEND_INVITATION_SERVICE = "SEND_INVITATION_SERVICE",
  HASH_SERVICE = "HASH_SERVICE",
}
