export const ProbaNotesDiToken = {
  PROBA_NOTES_REPOSITORY: Symbol("PROBA_NOTES_REPOSITORY"),
  CREATE_NOTE_USE_CASE: Symbol("CREATE_NOTE_USE_CASE"),
  UPDATE_NOTE_USE_CASE: Symbol("UPDATE_NOTE_USE_CASE"),
  DELETE_NOTE_USE_CASE: Symbol("DELETE_NOTE_USE_CASE"),
}
