export enum UserDiToken {
  GET_USER_USE_CASE = "GET_USER_USE_CASE",
  UPDATE_USER_USE_CASE = "UPDATE_USER_USE_CASE",
  USER_REPOSITORY = "USER_REPOSITORY",
  GET_SCOUT_BY_FOREMAN_EMAIL_USE_CASE = "GET_SCOUT_BY_FOREMAN_EMAIL_USE_CASE",
  REMOVE_SCOUT_FROM_GROUP_USE_CASE = "REMOVE_SCOUT_FROM_GROUP_USE_CASE",
}
