export enum InvitesDiToken {
  ACCEPT_INVITE_USE_CASE = "ACCEPT_INVITE_USE_CASE",
  SEND_INVITE_USE_CASE = "SEND_INVITE_USE_CASE",
  INVITES_REPOSITORY = "INVITES_REPOSITORY",
  SEND_INVITATION_SERVICE = "SEND_INVITATION_SERVICE",
}
